### ISSUE TITLE
Drop the algebraicity condition

### ISSUE THREAD

**Issue by jcommelin** [jcommelin/superficie-algebriche#14]
It shouldn't be too hard to extend to the full E-K classification.
If we restrict to the complex numbers, I guess we only have to add

* Class VII surfaces
* Kodaira surfaces (primary, secondary)
* complex tori
* non-algebraic K3's (in some sense they are already there)

We might want to add a checkbox somewhere, so that people can restrict to algebraic surfaces (maybe als Kähler?)

**Comment by pbelmans** [comment]
Shouldn't be too hard indeed, but I'd rather have more examples in there for algebraic surfaces. At the moment, everything except the line \chi=1 looks like Siberia, e.g. we need things like the Horikawa surfaces. I'm planning to take a look at these things this weekend.

**Comment by jcommelin** [comment]
Reason I added this issue, is that there is a seminar on E-K classification running in Utrecht, right now. So, maybe I can make some people enthousiastic for adding some data to our db. But since most of them are not AG'rs, we should probably allow them to add non-algebraic stuff. But we can think about the roadmap a bit, before plunging into it.

**Comment by pbelmans** [comment]
I think it's best to first redo the data structure for surfaces, and computing all invariants in there. Then displaying numerical invariants will become independent of algebraicity. If time permits I'll implement these things over the weekend.

**Comment by pbelmans** [comment]
Well, I guess this can be closed. The functionality is there, the user interface could be improved a little, and now we just need someone to punch in the data.
