### ISSUE TITLE
The slider in Firefox looks ugly

### ISSUE THREAD

**Issue by jcommelin** [jcommelin/superficie-algebriche#15]
Currently it's pretty hard to drop the slider on 0 or 1. Ideally it should become more like in Chrome, or maybe a dropdown, or a cluster of radio buttons.

![2015-01-16-144657_253x41_scrot](https://cloud.githubusercontent.com/assets/5636705/5776907/e97e15f8-9d8d-11e4-8f14-c38d85855ef8.png)

**Comment by pbelmans** [comment]
We don't design the slider. The browser renders it, and there is not much control over it... Moreover, in my Firefox it looks like the slider in Chrome (but without the marks), and totally unlike yours. It might be related to your probably insanely obscure window manager in Linux :).

**Comment by jcommelin** [comment]
Aah, ok. So then there is also no way to detect it. Well, I'll have to live with it then. Alternatively, we use jqueryui or something like that, to build a slider. But I guess that is a bit overkill.
You'll probably counter that I just need to install the right GTK libraries… fair enough.

**Comment by pbelmans** [comment]
We could use some JQueryUI slider, but the only people with issues are people using obscure window managers without GTK libraries, and these have more important issues to deal with ;).

Let's say: if someone at some point complains, we'll reopen.
