### ISSUE TITLE
Hodge diamond is not reset to '?' after an autoselected surface

### ISSUE THREAD

**Issue by jcommelin** [jcommelin/superficie-algebriche#18]
Reproduce:

1. Select invariants with only one candidate (it is autoselected). [E.g., (c2 = 15, c12 = 21)]
2. Select invariants with more than one candidate. [E.g., (c2 = 4, c12 = 8)]

They Hodge diamond of the first selection is still visible, though greyed out.

**Comment by pbelmans** [comment]
I can't reproduce this.

**Comment by jcommelin** [comment]
I also no longer can reproduce this.
